### ISSUE TITLE
Style issues when building the docs with (future) Sphinx 2.0

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#13591]
### Bug report

I've just build the matplotlib docs with sphinx master (future 2.0) and some of the styling has gone bad:

***Edit:* Let's collect all the doc rendering problems in this issue, so that we know what we have to fix later on:**

#### List of issues:

- [x] Numpydoc parameters section title rendered incorrectly (see below in this comment, @dstansby: fixed in sphinx 2.1.2)
- [x] No space between parameter names and types in numpydoc parameters sections (see below in this comment, upstream bug: https://github.com/numpy/numpydoc/issues/215, , fix in #14105).
- [x] Some headlines broken (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478238632, fixed in sphinx 2.1)
- [x] Wrapping after bullet points in table of contents (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478263720, fix in #14105)
- [ ] Table rendering (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478264291)
- [ ] Rendering of list of methods (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478264615)
- [x] Search is broken (https://github.com/matplotlib/matplotlib/issues/13591#issuecomment-478306881, fixed in sphinx 2.0.1)

### Issue: Numpydoc parameters section

![image](https://user-images.githubusercontent.com/2836374/53771527-30477b00-3ee3-11e9-8eae-b61e84f35e44.png)

[ ] Need to check if there will style changes in sphinx 2.0 and possibly adapt mpl.css.

**Comment by ImportanceOfBeingErnest** [comment]
Yes, equally, some headlines are broken, as in [the pyplot tutorial](https://matplotlib.org/devdocs/tutorials/introductory/pyplot.html).

![image](https://user-images.githubusercontent.com/23121882/55275729-89d87500-52ea-11e9-9f7d-fd988ac7b23c.png)

**Comment by timhoffm** [comment]
Issue: Wrapping after bullet points in table of contents

![image](https://user-images.githubusercontent.com/2836374/55279094-c3be7100-5314-11e9-942f-6feddea5872a.png)

**Comment by timhoffm** [comment]
Issue: Table rendering

![image](https://user-images.githubusercontent.com/2836374/55279134-4e06d500-5315-11e9-8f8a-9bac6686ebb6.png)

**Comment by timhoffm** [comment]
Issue: Rendering of list of methods (might be the same as table rendering above)

![image](https://user-images.githubusercontent.com/2836374/55279153-8a3a3580-5315-11e9-804a-48d17a4a1ad7.png)

**Comment by ImportanceOfBeingErnest** [comment]
For me, the [search](https://matplotlib.org/devdocs/search.html?q=contour) is broken as well. But someone could verify if this is only a problem with my browser locally.

**Comment by timhoffm** [comment]
Yes, search is broken as you can see in recent CI builds:
https://19829-1385122-gh.circle-artifacts.com/0/home/circleci/project/doc/build/html/index.html

That may or may not be an issue to solve on our side.

**Comment by tacaswell** [comment]
How many of these are things we need to cope with and how many of them are issues that should be reported back to sphinx as regressions?

**Comment by timhoffm** [comment]
Needs investigation. On the practical side, I think we have to fix most of this in matplotlib. I don't know how aware sphinx is of these changes since I did not see anything about it in the changelog. But I doubt they will go back.

**Comment by dstansby** [comment]
I've put this as release critical (for `3.2`) so we don't forget about it - I'll try to have a look into some of the problems soon.

**Comment by dstansby** [comment]
The search not working was a sphinx problem, fixed in `2.0.1`, so I have ticked it above.

**Comment by dstansby** [comment]
So it looks like fixing the CSS will be not preserve backwards compatibility with sphinx < 2. I might have a go at fixing it, and then we can just leave the PR until we decide to switch from sphinx 1 to sphinx 2 in the future.

**Comment by timhoffm** [comment]
Alternatively, you can add a new `mpl-sphinx2.css` and set `html_style` in `conf.py` conditionally on the sphinx version. That way, we do not need a hard cut, which may make the transition easier.
