### ISSUE TITLE
Add pull request checklist to Reviewers Guidlines

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#15280]
In the Reviewers Guideline, there's a section called [Pull Request Checklist](https://matplotlib.org/devel/coding_guide.html#pull-request-checklist) tthat doesn't have a checklist. What about adding one in that section as a sort of intro/framing/table of contents for the rest of the page? 

The jumping off point could be the checklist @timhoffm so helpfully provided:

Nevertheless, here's a condensed checklist of the thing to check before merging:
- [ ] Check that the PR targets the master branch
- [ ] Check/set labels
- [ ] Check/set milestone
- [ ] Check that tests still pass
- [ ] Check that the PR does not have excessive commits. One or a few semantically grouped commits should do (in particular less experienced github users tend to commit all their changes in sequence). If there are too many, ask the author to squash, or use "Squash and Merge" button in the github UI.

_Originally posted by @timhoffm in https://github.com/matplotlib/matplotlib/pull/15252#issuecomment-531570512_

Yes, should probably just put in this PR, writing it up as an issue so that I don't forget and it's out there for anybody to do.
