### ISSUE TITLE
Consolidate Install Docs 

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#17327]
Installation is documented in at least 4 places:
* [users/installing](https://matplotlib.org/devdocs/users/installing.html)
* [contributing/retrieve latest version of source install](https://matplotlib.org/devdocs/devel/contributing.html#retrieving-and-installing-the-latest-version-of-the-code)
* [FAQ/Installation](https://matplotlib.org/devdocs/faq/installing_faq.html)
* https://github.com/matplotlib/matplotlib/blob/master/INSTALL.rst

which can lead to them being out of sync, as seen by the issues targeting only one page in the docs, and can make it harder for new users (especially new contributors) to figure out which instructions they're supposed to be following. I propose the docs get consolidated down to one installation page, the section from the FAQ be removed, and that the developer docs & install.rst should cross link to that install page. 

In the process of consolidating the docs, the following issues should probably also at least be addressed:
- [ ] #6418  Update virtual env+osx+conda docs
- [ ] #8652  Windows build using conda
- [ ] #11702 Installing from source on windows
- [ ] #7418 Definitive Docs for Compilation on Windows
- [ ] #14755 uninstall existing versions of matplotlib
- [ ] #9994 Document nightly wheels location

**Comment by r0cketr1kky** [comment]
Hi @story645 , I would like to take this up.

**Comment by story645** [comment]
go for it!

**Comment by r0cketr1kky** [comment]
Do you want me to remove the entire `doc/faq` folder or only `doc/faq/installing_faq.rst`? I guess it's the latter but just wanted to confirm :)
Another doubt: I need to remove all these 4 files addressed in this issue and include these in the canonical install page and include the contents of all these 4 pages right, keeping the home page links as the canonical install instructions?

**Comment by story645** [comment]
My suggestion is to consolidate everything in the the users/install page & maybe keep the existing files but replace the text with a link back to the install instructions.

**Comment by r0cketr1kky** [comment]
Sounds like a plan. I'm on it :)

**Comment by timhoffm** [comment]
I recommend to keep installation for development in the contribution docs. The two locations address different audiences and having a long page of installation instructions may be intimidating for a simple user (even though he might only need a fraction of the page).

Also "Installing for development" is not useful by itself. It needs to be done in context with cloning the repo and setting up a development env (virtualenv/conda/...).

On https://matplotlib.org/devdocs/users/installing.html I would add a section "Installing for development" and have there just a link to the contribution docs.

**Comment by story645** [comment]
@timhoffm that's fine with me so long as the install from source docs are in one place. I'm fairly certain the top bug for new contributors is that they're using the wrong install instructions.

**Comment by rajpratyush** [comment]
@story645 does this issue needs work?

**Comment by jklymak** [comment]
It doesn't seem done to me.  We could move any useful info from the FAQ to INSTALL.rst.  A quick look at INSTALL.rst, it could probably be trimmed substantially.  If we need an "Advanced Installation" page, that might make sense, but I wouldn't call it a FAQ.   @rajpratyush if you think you understand the install well enough to try and merge, feel free to give it a shot.

**Comment by timhoffm** [comment]
Part of this will be adressed with #19505. Further work should be based on that.

Btw. as a friendly reminder, it would be great if someone would review #19505.

**Comment by SauravMaheshkar** [comment]
Should this issue be closed after #19725 and #19505 ?
