### ISSUE TITLE
[MNT]: Pybind11 transition plan

### ISSUE THREAD

**Issue by ianthomas23** [matplotlib/matplotlib#23846]
We intend to switch the C/C++ extension build system to use `pybind11` as discussed in this week's call. There is a demonstration in PR #23787 showing that the approach works and listing the pros and cons. It is too much work to do in a single PR so will probably be done one extension at a time. This issue is intended to track the overall progress by editing this post to tick the relevant check box and add the PR number for each extension completed.

C/C++ extensions:
  - [x] `agg` (start in #27011)
  - [x] `c_internal_utils` (PR in #26794)
  - [x] `ft2font` (PR in #28785)
  - [x] `image` (implemented in #26275)
  - [x] `path`  #27087
  - [x] `qhull`(PR in #27184)
  - [x] `tkagg` (PR in #26992)
  - [x] `tri` (implemented in #24522)
  - [x] `ttconv` (implemented in #25253)
  - [x] ~~`macosx` (developer needs access to macOS)~~

Other work required:
  - [x] Update to use PEP517/518-complicant build system. Not strictly required but makes the build process simpler so ideally would be done before merging any specific extension PRs. Work on this has started in #23829; for `pybind11` we only really need the `[build-system]` section of `pyproject.toml` which was added in #24102.
  - [ ] Remove unneeded wrapper code in `src` directory such as the `array_view` class when all extensions completed. #28857
  - [ ] Remove `numpy` as a build-time dependency when all extensions completed as `pybind11` does not require it. #28857

**Comment by QuLogic** [comment]
On a related note, has anyone tried out [nanobind](https://nanobind.readthedocs.io/en/latest/index.html)? It's probably a bit too new for us, but curious if anyone had any opinions on it.

**Comment by matthewfeickert** [comment]
> On a related note, has anyone tried out [nanobind](https://nanobind.readthedocs.io/en/latest/index.html)? It's probably a bit too new for us, but curious if anyone had any opinions on it.

I _just_ today [migrated a (small) research project](https://gitlab.cern.ch/gstark/pycolumnarprototype/-/merge_requests/10) to `nanobin` `v1.0.0`.

As this project is array heave `nanobin` is _super_ nice for this as it allows you to just use the `nb::ndarray` API and avoid all the buffer stuff in `pybind11` (which honestly isn't that bad, but if you don't have to do it yourself that's great).

Other advantages that are nice about `nanobind` (YMMV though project to project):

> More concretely, [benchmarks](https://nanobind.readthedocs.io/en/latest/benchmark.html#benchmarks) show ~2-3× faster compile time, ~3× smaller binaries, and up to ~8× lower runtime overheads compared to pybind11.
- https://nanobind.readthedocs.io/en/latest/index.html

> nanobind can exchange n-dimensional arrays (henceforth “ndarrays”) with popular array programming frameworks including [NumPy](https://numpy.org/), [PyTorch](https://pytorch.org/), [TensorFlow](https://www.tensorflow.org/), and [JAX](https://jax.readthedocs.io/). It supports zero-copy exchange using two protocols:
>
> * The classic [buffer protocol](https://docs.python.org/3/c-api/buffer.html).
> * [DLPack](https://github.com/dmlc/dlpack), a GPU-compatible generalization of the buffer protocol.
>
> nanobind knows how to talk to each framework and takes care of all the nitty-gritty details.

- https://nanobind.readthedocs.io/en/latest/ndarray.html

My first impressions are that it is great!

**Comment by QuLogic** [comment]
>     * [ ]  `macosx` (developer needs access to macOS)

I'm not sure about this one, as it doesn't use NumPy, and is written in Objective C, not C or C++.

**Comment by greglucas** [comment]
> >* [ ]  `macosx` (developer needs access to macOS)

> I'm not sure about this one, as it doesn't use NumPy, and is written in Objective C, not C or C++.

I agree pybind doesn't seem like the right fit. I have wondered if it'd be worthwhile to transition to use pyobjc at all so we could write the extension in Python code... https://pyobjc.readthedocs.io/en/latest/
Of course, that would mean an extra dependency on macos and needing to learn how to write that style of Python.

**Comment by QuLogic** [comment]
The last PR #28785 does ft2font. After that there will be some clean up to remove the NumPy wrappers.

**Comment by QuLogic** [comment]
The last two PRs: #28856 takes care of porting remaining common functionality to pybind11, and #28857 removes NumPy and the helpers.
