### ISSUE TITLE
[MNT] Tracking issue: GitHub codespaces

### ISSUE THREAD

**Issue by melissawm** [matplotlib/matplotlib#26169]
### Summary

Recently, [we added](https://github.com/matplotlib/matplotlib/pull/26137) support for [GitHub codespaces](https://docs.github.com/en/codespaces). With this configuration, contributors can open a pre-configured development environment and get started with contributing to Matplotlib right away from their browser.

If you go to matplotlib/matplotlib or your own fork (**preferred**) and choose "Create codespaces on `<branch>`":
![Screenshot_20230616_155713](https://github.com/matplotlib/matplotlib/assets/3949932/ba9ecea0-d5af-4383-8614-fa96869dcadf)

This will open a browser window with a VSCode interface and a pre-installed development environment built over an Ubuntu image.  You can then do

```
$ conda activate mpl-dev
$ python -m pip install -e .
```

After that you can run tests, build the documentation and run other commands.

This configuration also includes a [lightweight fluxbox environment](https://github.com/devcontainers/features/tree/main/src/desktop-lite)

This is a tracking issue to gather feedback and ideas for improvement on the codespaces configuration.

Pending tasks are:

- [ ] documentation on how to use it and current features (like connecting to the fluxbox desktop to see plots).
- [ ] auto-activate the conda environment (currently a limitation of codespaces)
- [ ] have pre-commit automatically installed
- [ ] suggest creating a new feature branch instead of committing to the main branch (important for new contributors)

**Comment by timhoffm** [comment]
As a remark: By default, `README.md` is opened in the online editor. Maybe one can change that so that we can show a page with targeted information on the use of codespaces.

**Comment by melissawm** [comment]
I haven't found a good way to preview a markdown file (instead of just opening it) so I opened a ticket here: https://github.com/orgs/community/discussions/59435

**Comment by melissawm** [comment]
Should we close this issue or keep as a general catch-all for codespaces issues?

**Comment by story645** [comment]
Your call?

**Comment by melissawm** [comment]
I'll close and we can open dedicated issues if problems arise. Thanks!
