### ISSUE TITLE
[TST]: increase unit test coverage 

### ISSUE THREAD

**Issue by tacaswell** [matplotlib/matplotlib#26864]
# Problem

Although we nominally support units through all of our plotting APIs, this is not through tested (unfortunately this is a case where code coverage is not super informative).   The address this issue we would like to add a "smoke test" (does it run without smoke coming out?) of every plotting method using "unit-full" data.  The most common "unit-full" data is likely datetime, thus we are going to use datetime and timedelta values as the vehicle to exhaustively test which of the methods correctly handle units.

This is the tracking issue for this work.

# Process

1. Fork Matplotlib and get set up for development. See https://matplotlib.org/devdocs/devel/contribute.html#contribute-code for detailed instructions of setting up a local or codespaces development environment.  For this work it is not strictly necessary to have a development version of Matplotlib installed, just an up-to-date installation (mpl 3.8.0) as the tested behavior _should_ be stable.
2. Select a method to work on (for GHC OSD we will use slack and zoom to make sure we de-conflict!)
3. Develop a short example that exercises passing dates or time deltas into the plotting methods.  Try to exercise as many of the inputs (and their combinations) as practical with the datetimes.
    1. If you have a working example open a Pull request adding the example as a body to the correct test method in `lib/matplotlib/tests/test_datetime.py`. Please include an image of the generated plot in the description of the PR and cross reference this issue (by including `#XXXX` in the PR description body).  This is modeled for `ax.plot` (I took the easiest one ;) ) in #26859.
    2. If you find a method that _should_ support datetime input but does not, open a new bug with the broken code and similarly reference this issue.
    3. If passing datetime / united data to the method does not make any sense or it should not work open a PR removing that test method and similarly reference this issue.

# Task list

 - [ ] `Axes.acorr`
 - [ ] `Axes.angle_spectrum`
 - [ ] `Axes.annotate`
 - [ ] `Axes.arrow`
 - [ ] `Axes.axhline`
 - [ ] `Axes.axhspan`
 - [ ] `Axes.axline`
 - [ ] `Axes.axvline`
 - [ ] `Axes.axvspan`
 - [ ] `Axes.bar`
 - [ ] `Axes.bar_label`
 - [ ] `Axes.barbs`
 - [ ] `Axes.barh`
 - [ ] `Axes.boxplot`
 - [ ] `Axes.broken_barh`
 - [ ] `Axes.bxp`
 - [ ] `Axes.clabel`
 - [ ] `Axes.cohere`
 - [ ] `Axes.contour`
 - [ ] `Axes.contourf`
 - [ ] `Axes.csd`
 - [ ] `Axes.errorbar`
 - [ ] `Axes.eventplot`
 - [ ] `Axes.fill`
 - [ ] `Axes.fill_between`
 - [ ] `Axes.fill_betweenx`
 - [ ] `Axes.hexbin`
 - [ ] `Axes.hist`
 - [ ] `Axes.hist2d`
 - [ ] `Axes.hlines`
 - [ ] `Axes.imshow`
 - [ ] `Axes.loglog`
 - [ ] `Axes.magnitude_spectrum`
 - [ ] `Axes.matshow`
 - [ ] `Axes.pcolor`
 - [ ] `Axes.pcolorfast`
 - [ ] `Axes.pcolormesh`
 - [ ] `Axes.phase_spectrum`
 - [ ] `Axes.pie`
 - [x] `Axes.plot`
 - [ ] `Axes.plot_date`
 - [ ] `Axes.psd`
 - [ ] `Axes.quiver`
 - [ ] `Axes.quiverkey`
 - [ ] `Axes.scatter`
 - [ ] `Axes.semilogx`
 - [ ] `Axes.semilogy`
 - [ ] `Axes.specgram`
 - [ ] `Axes.spy`
 - [ ] `Axes.stackplot`
 - [ ] `Axes.stairs`
 - [ ] `Axes.stem`
 - [ ] `Axes.step`
 - [ ] `Axes.streamplot`
 - [ ] `Axes.table`
 - [ ] `Axes.text`
 - [ ] `Axes.tricontour`
 - [ ] `Axes.tricontourf`
 - [ ] `Axes.tripcolor`
 - [ ] `Axes.triplot`
 - [ ] `Axes.violin`
 - [ ] `Axes.violinplot`
 - [ ] `Axes.vlines`
 - [ ] `Axes.xcorr`

**Comment by seohyeon-lee-2025** [comment]
Hello! I'll take Axes.scatter

**Comment by tgmiller5** [comment]
Hello, I will take the axes.bar

**Comment by ayushrathore111** [comment]
hii @tacaswell
 I'll start working on Axes.boxplot.
thank you.

**Comment by ksunden** [comment]
Note we are testing `matplotlib` unit support here, so please use numpy/matplotlib/datetime only in these tests (e.g. not pandas)

**Comment by kots14** [comment]
Hi @tacaswell 
I'm starting to work on Axes.contour.

**Comment by Quetzalcoatl29** [comment]
Hi @tacaswell I'd like to be assigned on one or more tasks

**Comment by rcomer** [comment]
Hi @Quetzalcoatl29, we do not assign tasks.  Please work on whichever one you like.  If you comment to say which you are starting on, as others have done, then that will help to prevent duplication of effort.

**Comment by kots14** [comment]
I'll be working on `Axes.contourf` next once this [PR](https://github.com/matplotlib/matplotlib/pull/27013) is merged.

**Comment by yangyangdotcom** [comment]
I will work on  Axes.hist

**Comment by yangyangdotcom** [comment]
I am able to write the test and run it with no failure but I am having a problem generating the graph. I tried adding plt.show() at the end of my test but that will make the test fail. Any help would be much appreciated.

**Comment by tgmiller5** [comment]
I decided not to do the bar plot anymore. But thanks.

**Comment by kots14** [comment]
Okay, I'll try out `Axes.bar`.

**Comment by QuadroTec** [comment]
Hello! I'll start working on Axes.stackplot

**Comment by kots14** [comment]
I'm working on `Axes.plot_date`.
Also, I'm waiting for reviews on these PRs -
- https://github.com/matplotlib/matplotlib/pull/27033
- https://github.com/matplotlib/matplotlib/pull/27024

**Comment by CozyFrog** [comment]
I will work on Axes.barh.

**Comment by danielcobej** [comment]
I will work on Axes.axvspan and Axes.axhspan

**Comment by jklymak** [comment]
I crossed out the spectral ones - arguments aside about whether they should be part of Matplotlib, they don't have units as arguments.

**Comment by Sheepfan0828** [comment]
Hello! Can I just solve the `Axes.pie` problem?

**Comment by rcomer** [comment]
@Sheepfan0828 please do!

**Comment by Sheepfan0828** [comment]
@rcomer how can i create a branch to work with? I have forked this repo to my own account as the local repo and then cloned it into my own machine.

**Comment by Sheepfan0828** [comment]
@story645 I have checked with that, is that means i just need to create the branch for the repo that i have forked into, and then after the changes have been submitted to this branch, i just make the pull request in my forked repo so that you will approve my branch to be merged into the main repo, not just the my forked one?

**Comment by ksunden** [comment]
All pull requests (with very few exceptions), including those from core contributors come from our personal forks, you do not need to have a branch on the base repo before making a pull request.

**Comment by Sheepfan0828** [comment]
I have done `pie` problem now, and it is removed from the project file since we cannot directly pass the `datetime` object into the `pie` function as a parameter so that `pie` function is not testable with `datetime` object. But now i see someone is doing the `scatter` but haven't solved it yet, can i just do `scatter` problem?

**Comment by CozyFrog** [comment]
I am currently working on Axes.axhline.

**Comment by naychithanshwe** [comment]
I will work on Axes.bar_label

**Comment by kots14** [comment]
I'm working on `Axes.xcorr`.

**Comment by mliu08** [comment]
Working on Axes.annotate

**Comment by ElisaHeck** [comment]
I will work on Axes.barbs

**Comment by samchan2022** [comment]
will work on Axes.arrow

**Comment by pandyah5** [comment]
I would like to work on Axes.streamplot ! 😄

**Comment by rawwash** [comment]
Working on axes.bxp! Will shortly submit a PR

**Comment by nidaa-7** [comment]
hello, I am working on axes.fill

**Comment by linyilily** [comment]
hello, I am working on axes.fill_between

**Comment by ifEricReturnTrue** [comment]
Hello, I wan working on Axes.stairs

**Comment by xieruoyi** [comment]
Hello, I am working on Axes.fill_betweenx.

**Comment by avramid9** [comment]
Hello, I will be working on Axes.xcorr

**Comment by dchen2438** [comment]
Hi, I'm working on Axes.acorr

**Comment by nidaa-7** [comment]
Hello, I will work on axes.pcolormesh!

**Comment by AndyXi163** [comment]
Hi! I will take Axes.pcolorfast()!

**Comment by Dkjam5511** [comment]
Hi! I'll take Axes.quiverkey

**Comment by tracyqian0720** [comment]
Hi, I will be taking adding datetime testing for boxplot! #27038

**Comment by tracyqian0720** [comment]
hi I will be taking on Axes.plot()

**Comment by ksunden** [comment]
@tracyqian0720 note that plot is checked off as completed (it was the example one, just never got linked here)

**Comment by tracyqian0720** [comment]
thanks @ksunden I'll take Axes.violin then!

**Comment by shriyakalakata** [comment]
HI, I will work on Axes.event plot!

**Comment by bikegeek** [comment]
I'll work on Axes.hexbin

**Comment by ConstableCatnip** [comment]
I'll work on matshow

**Comment by nyeshlur** [comment]
I'll work on Axes.streamplot

**Comment by szhukovska** [comment]
Hi all, I'll work on Axes.tricontour

**Comment by bikegeek** [comment]
I'll work on Axes.tripcolor

**Comment by ConstableCatnip** [comment]
...and imshow

**Comment by AliAboelela123** [comment]
I’ll work on Axes.clabel

**Comment by mtanvi19** [comment]
I will work on Axes.violinplot.

**Comment by AsherHounsell** [comment]
I will work on Axes.triplot.

**Comment by EthanZheng11** [comment]
I will work on Axes.tricontourf.

**Comment by jhimanish** [comment]
Hi, I'm new to Open-Source Contributions but I'd like to contribute towards this project. I can work on creating a test for axes.streamplot.
Thank you

**Comment by ksunden** [comment]
I do believe we now have PRs (at least) opened for each of these.

Thank you to all of the first time contributors who helped get us this far.

**Comment by Elllllllvin** [comment]
Hello , I would like to tackle the Axes.quiver if you don't mind, since i notice that it has not been solved yet.

**Comment by ksunden** [comment]
Please note that we have an open PR for Quiver, and we generally prefer the earlier PR when possible. https://github.com/matplotlib/matplotlib/pull/27407

**Comment by ksunden** [comment]
I'm removing the good first issue tag because we have PRs at least started for all points here.

**Comment by Elllllllvin** [comment]
> Please note that we have an open PR for Quiver, and we generally prefer the earlier PR when possible. #27407

Thank you for your reply. I just noticed that the previous [#27407 ](https://github.com/matplotlib/matplotlib/pull/27407) did not fully solve the problem. It only tested X and did not test Y, and the previous pull request has not been merged, so I thought I could continue to contribute to this issue.
