### ISSUE TITLE
[Doc]: regularize doc formatting

### ISSUE THREAD

**Issue by story645** [matplotlib/matplotlib#26862]
### Documentation Link

https://matplotlib.org/devdocs/devel/document.html#section-formatting

### Problem

We acknowledge in our docs that we haven't completely moved our docs over to our specified format, which sometimes creates cascading effects when trying to combine/reorganize docs- directives like `..include` don't like the mismatch and when reading the docs it can make it hard to figure out what level a given section is supposed to be at. 

### Suggested improvement

Reformat docs as needed so that they conform to the guidelines. 
> Use [sentence case](https://apastyle.apa.org/style-grammar-guidelines/capitalization/sentence-case) Upper lower for section titles, e.g., Possible hangups rather than Possible Hangups.
> 
> We aim to follow the recommendations from the [Python documentation](https://devguide.python.org/documenting/#sections) and the [Sphinx reStructuredText documentation](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections) for section markup characters, i.e.:
> 
>     # with overline, for parts. This is reserved for the main title in doc/index.rst. 
> 
>     * with overline, for chapter. all pages except doc/index.rst should start with "chapter" or lower.
> 
>     =, for sections
> 
>     -, for subsections
> 
>     ^, for subsubsections
> 
>     ", for paragraphs

**NOTES**: 
* do not sentence case files under "/project" 
* ignore files in any "api_changes", "whats_new", or MEP file/folder.  
* do not add new headings without a justification. This issue is about converting **existing** heading markers into its  corresponding heading markers in the list above.

### Documents with old style formatting: 
This work is mostly converting ~~ to ^^^
Please post here which file you are working on:

#### project
- [x] [user/project/citing](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/doc/users/project/citing.rst?plain=1) https://github.com/matplotlib/matplotlib/pull/26995

#### API
- [x] [api/animation](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/doc/api/animation_api.rst?plain=1) https://github.com/matplotlib/matplotlib/pull/27348

#### contribute
- [x] [devel/contribute](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/doc/devel/contribute.rst?plain=1) #26961
- [x] [devel/document](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/doc/devel/document.rst?plain=1) #26754
- [x] [devel/release_guide](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/doc/devel/release_guide.rst?plain=1) #27118
- [x] https://github.com/matplotlib/matplotlib/pull/27039

#### user_guide
- [x] [user_guide/artists/artist_intro](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/artists/artist_intro.rst) #27036
- [x] [user_guide/figure/api_interfaces](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/figure/api_interfaces.rst?plain=1) #27043
- [x] [user_guide/figure/interactive](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/figure/interactive.rst?plain=1) #27054

##### text
- [x] [user_guide/text/text_intro](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/text/text_intro.py) #27096
- [x] [user_guide/text/fonts](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/text/fonts.py) #27096
- [x] [user_guide/text/mathtext](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/text/mathtext.py) #27096

###### toolkits
- [x] [user_guide/toolkits/axes_grid](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/toolkits/axes_grid.rst?plain=1)  #26985

#### tutorials
- [x] [tutorials/index](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/tutorials/index.rst?plain=1)  #26985

#### gallery
- [x] [examples/subplots_axes_and_figures](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/examples/subplots_axes_and_figures/axes_box_aspect.py) #27219
- [x] [examples/text_labels_and_annotations/angle_annotation](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/examples/text_labels_and_annotations/angle_annotation.py) #27219

**Comment by 15IITian** [comment]
Thank you for your response @story645 
Actually when I read for first time , I thought that  it should be made sub-section of `Draw first plot`.
But if my work  is not on right path , then  please clarify/guide me .

**Comment by 15IITian** [comment]
Thank you for your response @jklymak 
I understand organization's concerns .
Being new to open source , I thought to make smaller PR's in order to get comfortable with open-source & matplotlib .
Thus , there was no intention to increase my PR's no in hactoberfest ;)
I will keep this in mind now onwards .

**Comment by iamfaham** [comment]
I am working on the [user_guide/toolkits/axes_grid](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/toolkits/axes_grid.rst?plain=1) file.

**Comment by iamfaham** [comment]
Hey @story645 , I have created a PR in which i have updated 2 of the necessary docs. Let me know of any necessary changes to the same.

**Comment by AnviVerma27** [comment]
i will be working on this [user/project/citing](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/doc/users/project/citing.rst?plain=1)

**Comment by gargmonika** [comment]
Hey, I will be working on  api/animation  file.

**Comment by BS14** [comment]
Hey, I will be working on [user_guide/artists/artist_intro](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/artists/artist_intro.rst)

**Comment by Ruchir0403** [comment]
Can I work on this?

**Comment by BS14** [comment]
Hey, I will be working on [user_guide/figure/api_interfaces](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/figure/api_interfaces.rst?plain=1) and [user_guide/figure/interactive](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/users_explain/figure/interactive.rst?plain=1)

**Comment by dishafaujdar** [comment]
Hello , there I'll be working on TEXTS: user_guide/text/fonts

**Comment by Prince-Vijay-Santhosh** [comment]
Hi @story645, I would like to work on this issue, could you please assign me?

**Comment by aseriesof-tubes** [comment]
Hi! I'll be working on  [examples/subplots_axes_and_figures](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/examples/subplots_axes_and_figures/axes_box_aspect.py) and [examples/text_labels_and_annotations/angle_annotation](https://github.com/matplotlib/matplotlib/blob/78e366195deef21b0fac2c1b19c7b9b3dff9908a/galleries/examples/text_labels_and_annotations/angle_annotation.py).

**Comment by 0taj** [comment]
Hello, I'll work on devel/release_guide and api/animation

**Comment by gargmonika** [comment]
> Sure for release guide, give @gargmonika a bit to reply on if they're still planning on working on animation

Hey @story645 thanks for giving me chance. I really apologize i was really occupied with my full time work lately. I would surely still like to work on this . But if its under high priority and someone is available immediately, i don't mind
 to pass it on.

**Comment by Disha-Baghel** [comment]
May I contribute to unresolved tasks if someone isn't addressing their assigned issues?

**Comment by aseriesof-tubes** [comment]
Hi @Disha-Baghel and @story645, I'll be done with them shortly :)

**Comment by QuLogic** [comment]
api/animation is not done yet?

**Comment by raghuramsirigiri** [comment]
Can I work on api/animation? I want to start my open source contribution journey with this.
