### ISSUE TITLE
[MNT]: Remove 3.7-deprecated API

### ISSUE THREAD

**Issue by QuLogic** [matplotlib/matplotlib#26865]
# Summary

As old and unused API (classes, methods, functions) are found, they are marked deprecated with removal intended in a later release. These API are decorated or otherwise wrapped with [the deprecation functions in `_api`](https://github.com/matplotlib/matplotlib/blob/dceb278bef361f32eb0009dec5bfda41fc27fa38/lib/matplotlib/_api/__init__.py#L19-L22) (i.e., `deprecated`, `warn_deprecated`, `rename_parameter`, `delete_parameter`, `make_keyword_only`, `deprecate_method_override`, or `deprecate_privatize_attribute`).

Now that 3.8 is out and `main` targets 3.9, we can start the process of removing API that were deprecated in 3.7 (i.e., those with `since="3.7"` and without `pending=True`).

# Proposed fix

Each part of the deprecated API should be removed:
1. The deprecated code itself:
    a. Items marked with `_api.warn_deprecated`, `@_api.deprecated` or `@_api.deprecate_privatize_attribute` are to be removed on expiry, i.e., any of the marked lines below:
    ```diff
    -@api.deprecated("3.7", ...)
    -def foo():
    -    pass

     def bar(x):
         if x is None:
    -        _api.warn_deprecated("3.7", message="x=None is deprecated")
    +        raise ValueError("x=None is not supported")
        ...

     class Baz:
          ...
    -     value = _api.deprecate_privatize_attribute("3.7", ...)
    ```
    b. Items decorated with `@_api.rename_parameter` should have this decorator removed, and no other changes will be necessary (the parameter rename should already have been made when the decorator was added.), i.e.,
    ```diff
    -@_api.rename_parameter("3.7", "old_name", "new_name")
     def foo(new_name):
        ...
    ```
    c. Items decorated with `@_api.make_keyword_only` should have the decorator removed, and the parameter named there should be made keyword-only (by adding a `*` before that point).
    ```diff
    -@_api.make_keyword_only("3.7", "arg3")
    -def foo(arg1, arg2, arg3, arg4):
    +def foo(arg1, arg2, *, arg3, arg4):
        ...
    ```
    d. Items decorated with `@_api.delete_parameter` will need to have the parameter deleted _and_ all following parameters made keyword-only.
    ```diff
    -@_api.delete_parameter("3.7", "arg3")
    -def foo(arg1, arg2, arg3, arg4):
    +def foo(arg1, arg2, *, arg4):
        ...
    ```
3. The corresponding type stub in the related `*.pyi` file.
4. Any tests for _only_ deprecated behaviour.
5. Any related exceptions in `ci/mypy-stubtest-allowlist.txt`, if there are any.

Additionally, the removal should be documented by placing a snippet in `doc/api/next_api_changes/removals/` (see `00001-ABC.rst` in that directory for a template). For writing these snippets, you may wish to [copy the original deprecation notice](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.7.0.html#deprecations), modifying it slightly to state that the API has been removed instead. Please ensure that any references to deleted API include a full path (as there may be many methods with the same name, but on different classes.)

**NOTE**: After removing the deprecated API, there may be some additional fallout that should be corrected. For example,
1. Removed code may be aliased by importing in another location, so those imports will have to be removed.
2. Documentation may link to the removed API; these should be kept in code style. For example,
    ```rst
    This is some text referencing :class:`.RemovedClass`.
    ```
    should be changed to:
    ```rst
    This is some text referencing ``matplotlib.submodule.RemovedClass``.
    ```
    (Please expand the API into the full import name.)

See also [our documentation on removing deprecated API](https://matplotlib.org/devdocs/devel/contribute.html#expiring) and #26853 for an example removing several types of deprecated API.

# Task list
A quick search shows the following sets of possible parts to remove (for GHC OSD, please use Slack and/or Zoom to make sure someone else hasn't started working on the same set):
1. [x] `lib/matplotlib/animation.py` - 2 deprecations #26872
4. [x] `lib/matplotlib/axis.py` - 1 deprecation #26871
5. [x] `lib/matplotlib/backends/*.py` - 3 deprecations and `src/_backend_agg_wrapper.cpp` - 2 deprecations #26962
6. [x] `lib/matplotlib/cm.py` - 2 deprecations (Note: the documentation for this removal may be a bit tricky to write.) #26965
7. [x] `lib/matplotlib/contour.py` - 5 deprecations  #26907
8. [x] `lib/matplotlib/collections.py` - 2 deprecations #26874
9. [x] `lib/matplotlib/_fontconfig_patterns.py` - 1 deprecation #26884
10. [x] `lib/matplotlib/gridspec.py` - 1 deprecation  #26885 (!)
11. [x] `lib/matplotlib/lines.py` - 2 deprecations  #26902
12. [x] `lib/matplotlib/offsetbox.py` - 3 deprecations  #26910 ~~#26880~~
13. [x] `lib/matplotlib/patches.py` - 1 deprecation #26890 #26876 #26900 (!)
14. [x] `lib/matplotlib/quiver.py` - 2 deprecations #26918 
15. [x] `lib/matplotlib/tri/*.py` - 8 deprecations  #26909 
16. [x] `lib/mpl_toolkits/axisartist/axislines.py` - 2 deprecations #26900

There may be some other items I've missed here, but note that we do not want to remove any with `pending=True`, or `since="3.8"` or higher.

**Comment by QuLogic** [comment]
> If there is an open PR, please collaborate on the work by reviewing it rather than duplicating it in a competing PR.

Note that we expect to have PRs for smaller chunks here, so even if there are open ones, there might still be some chance to work on this issue; see the checklist above.

**Comment by mishrakushal** [comment]
Hello. This is my first time trying to contribute to open source. I went through the documentation and guidelines, as well as looked at the code. But I'm still not sure how to start. Could you please guide me?

**Comment by DHClimber** [comment]
Change in progress lib/matplotlib/contour.py #

**Comment by GAuravY19** [comment]
Hi,
I am a beginner t0 open-source contributions. I want to start my open-source contribution journey with this issue. 

Can anyone please tell me how I should start with this issue...?

**Comment by GAuravY19** [comment]
Hi Sir, 

For the first time, I am doing open source contribution.
I have tried to remove the deprecated function from ```src/_backend_agg_wrapper.cpp```. 

I want to share with you my work so that I can know whether I have the right job or not. Will you please guide me with the steps to create a pull request and send you my work for reviewing?

**Comment by GAuravY19** [comment]
It would be very helpful if you also guide me with what I have done wrong and how I can correct it.

**Comment by ksunden** [comment]
Please see our [contributing guide](https://matplotlib.org/stable/devel/contribute.html#how-to-contribute)

**Comment by QuLogic** [comment]
Note quite finished.

**Comment by Yen-yen** [comment]
Hi,
This will be my first contribution. After reading the contributing guide, I would like to start with this. Is anyone working on this right now?

**Comment by tacaswell** [comment]
@Yen-yen I think we have open PRs for all of these already.  This may not be a good issue to start on right now.

**Comment by Yen-yen** [comment]
> @Yen-yen I think we have open PRs for all of these already. This may not be a good issue to start on right now.

Got it. Thank you so much. I will look into another one!

**Comment by QuLogic** [comment]
I believe this is now complete.
