### ISSUE TITLE
[ENH]: Possible improvements for out-of-the-box interactivity

### ISSUE THREAD

**Issue by timhoffm** [matplotlib/matplotlib#28708]
### Problem

Compared to other visualization frameworks, matplotlib has very limited capability for interacting with the plot. I think we could do a bit better here.

There are two obstacles related to interactivity in Matplotlib:
1) By design, we have a one-way processing pipeline from data to a visual representation (pixels or vector primitives). Backtracking which data or Artist is responsible for a visual output is possible, but not quite easy. Additionally, any desired visual change requires a complete re-rendering.
2) We have multiple backends and want to provide consistency. This means, we have non-interactive backends that just can't provide interactivity. The interactivity we provide should work across all interactive backends.

1 is an architecture limitation, that we cannot easily circumvent. This means, we won't be high-perfoming and won't be able to support complex interactions. 2 also limits the complexity of interactions we can practically implement. OTOH it does not mean we cannot provide any interactivity at all. For example, we do have panning and zooming in interactive backends.

### Proposed solution

Let us consider which small improvements we can reasonably make to improve interactive experience. The following list should track interactivity ideas that seem prossible to implement under the current architecture with limited effort. Please feel free to add:

- [ ] Data tooltip support #23378
- [ ] Support panning and zooming using mouse scroll wheel #20317
- [ ] Toggling data via legend #16796

**Comment by timhoffm** [comment]
> What other general scientific visualization frameworks are you referring to here?

bokeh and plotly to name two popular examples. But basically you could take any javascipt or d3js based projects from https://pyviz.org/overviews/.

**Comment by ecstrema** [comment]
> > Compared to other visualization frameworks, matplotlib has very limited capability for interacting with the plot.
> 
> What other general scientific visualization frameworks are you referring to here?

Apart from matplotlib, I've only worked with pyqtgraph and plotly but matplotlib definitely lies behind here.

**Comment by timhoffm** [comment]
Better web/HTML integration is certainly on the wishlist. But IMHO it’s on the larger side of changes (write a new backend / improve ipympl). Additionally, serialization is partly orthogonal. It would improve communication between frontend and renderer, or move tasks to the frontend. Other interactive backends would benefit as well. Either way, it’s also a large-effort project (and I believe the data prototype is going that direction).

Both are out of scope for this collection. I‘m trying to find the low-hanging fruits that can be implemented in a reasonable one-PR effort. I believe the above mentioned topics fall into that category.

**Comment by jklymak** [comment]
For sure the state of various matplotlib/d3 based projects indicates that leveraging d3 is hard to get the abstractions correct.  D3 uses SVG and canvas, so perhaps using those primitives is the way to go.  This GSOC from 2019 https://blog.pyodide.org/posts/canvas-renderer-matplotlib-in-pyodide/ looks like it was very close to a working backend.  

However, agreed that this is more of a heavy lift than I think this issue is discussing.

**Comment by timhoffm** [comment]
Sure, documentation helps to discover what is available. However, „how to hook the wires up“ sounds like low-Level plumbing. Personally, my focus is out-of-the-box or simple configuration (e.g. add (static) tooltips via a `tooltip` argument)

**Comment by timhoffm** [comment]
I understood that. A tutorial for this may be nice, but it's not my scope here.

One a side-note: IMHO the "various out of the box things" are quite limited and low-level (basically, zoom/pan, picker, events/callbacks). We're missing a lot to make complex dashboarding easy (visual-to-data relation, layouting, good widgets, ...). There's a reason for additional explicit dashboarding libraries (e.g. panel or dash) built on top of the (already better interactive) js libraries. We will not be able to compete with those. Or to put it in another way: If you can reimplement medium-complexity dash or panel examples without significant more effort in Matplotlib, I'd be impressed and change my opinion.

So yes, showing that one can get a bit of interactivity and a simple dashboard is valuable. But as of now, I would not recommend matplotlib to anybody who wants to build more than the simplest of dashboards.

**Comment by timhoffm** [comment]
> who are you trying to target w/ these out-of-the box interactivity improvements

end-users, who just expect a little more interactivity.

> my suggestions

these suggestions are infrastructure behind the scenes, which may or may not be necessary. I come from the user side:
++
- data tooltip support: As written in the issue, I want that `plt.plot(range(4), range(4), tooltip=['A', 'B', 'C', 'D'])` **"just works"**. A bit analogous to how we set additional info with the legend `label`.
- Toggling data via legend: **No configuration**: Clicking legend entries could by default hide/show data (and fade the entry if data is hidden). This is a bit similar to the colorbar zooming we've implemented: We've added default interactive capability to existing elements that were previously static.
- Support panning and zooming using mouse scroll wheel: **Also no configuration**. Just add the functionality.

**Comment by jklymak** [comment]
> "here are the out of the box interactive things we provide" doc

https://matplotlib.org/stable/users/explain/figure/interactive.html#

**Comment by jklymak** [comment]
> That doc does not cover things like sharex/sharey or auto update colorbar scroll or the data cursor

Please open an issue or issues.

**Comment by jbednar** [comment]
> But also tagging @jbednar b/c he may have suggestions/opinions on what sorta interactivity would be good for mpl to provide.

I think I have the same concerns as mentioned by others above -- It will be very difficult to get full, nicely integrated interactivity with Matplotlib's current design, so it's important to focus on some limited subset that is better than what's available now, but is feasible.  But I also agree with @story645 that very few users make use of what's _already_ supported by Matplotlib.

So, if I were in charge of a small pot of money or developer time to spend, what I would personally direct that work to be is:

1. making basic cleanups to ipympl and particularly the icons and widgets to make what's already there be cleaner, nicely laid out, and "reasonable looking" in a web browser -- surely that's not a huge project! *Then*
2. documenting everything that's available and make it super easy for people to discover and use. *Then*
3. adding some limited additional interactivity as proposed in the first message here.

I.e., it seems like there's lots of low-hanging fruit just to make the interactive plotting look like it's from this millenium so that it doesn't feel quite so awkward to use, and then there's lots of outreach needed for most mpl users to even realize that this capability exists and is easy to invoke. At that point I'd add more interactivity, but for my part I think 1 and 2 are holding things back more than 3 is.

**Comment by jklymak** [comment]
> It will be very difficult to get full, nicely integrated interactivity with Matplotlib's current design,

I'm still curious what defines "nicely integrated interactivity" or if there is a package that exemplifies this?  I understand the three wishes above, but none of those are hard to implement with Matplotlib's current design.    But I'm curious what else would make things better?

**Comment by ianthomas23** [comment]
> > 1. making basic cleanups to ipympl and particularly the icons and widgets to make what's already there be cleaner, nicely laid out, and "reasonable looking" in a web browser
> 
> Not sure how much of that is part of the plan for @ianthomas23, who has been working on various ipympl improvements.

I don't have any plans for improving the appearance of ipympl, I'd much rather make it more resilient to upstream changes (in matplotlib, ipython and ipykernel).

**Comment by ecstrema** [comment]
IMO, docs come after out of the box interactivity. First you use it, _then_ you customize it. Customization is where you need docs.

And that's because as you said, a lot of these things are already available, but just poorly documented or not as easy to implement as they should be. So 1) add these:

> - Data tooltip support https://github.com/matplotlib/matplotlib/issues/23378
> - Support panning and zooming using mouse scroll wheel https://github.com/matplotlib/matplotlib/pull/20317
> - Toggling data via legend https://github.com/matplotlib/matplotlib/issues/16796

and then 2)

> documenting everything that's available and make it super easy for people to discover and use.

And for the last point:

> making basic cleanups to ipympl and particularly the icons and widgets to make what's already there be cleaner, nicely laid out, and "reasonable looking" in a web browser -- surely that's not a huge project!

From a user point of view, the widgets and buttons, although certainly feeling outdated, are a don't-care. As long as the plots look professional, and that I can interact with them, I don't care about what the buttons look like. It may not be a huge project, but as long as there is no canvas renderer, I don't see why anyone would use the web backend (the agg backend <-> web frontend is too slow).

**Comment by timhoffm** [comment]
> I don't see why anyone would use the web backend (the agg backend <-> web frontend is too slow).

To set perspective: I believe it's typically fast enough for on-time actions (think mouse-click), but not for continuous updates (mouse move).

**Comment by timhoffm** [comment]
> 1. making basic cleanups to ipympl and particularly the icons and widgets to make what's already there be cleaner, nicely laid out, and "reasonable looking" in a web browser -- surely that's not a huge project!

I'd expect this is mainly CSS, so could be done by almost anybody without having to know anything about matplotlib or ipympl.

**Comment by jklymak** [comment]
> See issue is we won't have a place to put the documentation

Google "Matplotlib interactivity" and the top hit takes you to https://matplotlib.org/stable/users/explain/figure/interactive.html.  So we do indeed have a place to put the documentation.
