### ISSUE TITLE
Migration to Py.test testing framework

### ISSUE THREAD

**Issue by Kojoley** [matplotlib/matplotlib#6731]
This task has been started in PR #5405, but ended without success, so I have decided to split it to multiple stages:
1. [x] Make `pytest` compatible with the current test suite
   - [x] Add support of unitest-like fixtures (`setUp` and other methods) on classes not derived from `unitest.UnitTest` (fixed with https://github.com/matplotlib/matplotlib/pull/6730/commits/8b64294b667ac4d5a7b95c8b1cad22766db6de66)
   - [x] Add support of `image_comparison` and `knownfailif` decorator (fixed with https://github.com/matplotlib/matplotlib/pull/6730/commits/bbaf7dc23fa92029fa9457e258a5ca4213c81851)
   - [x] Fix `raise KnownFailureTest` problems (PR #6730)
     - [x] `ImageComparisonTest.test`
     - [x] `test_axes.test_formatter_large_small`
     - [x] `test_backend_pgf.compare_figure`
     - [x] `test_animation.check_save_animation`
     - [x] `test_coding_standards.test_pep8_conformance_examples`
   - [x] `test_basic` leaks tests from `numpy` into global scope with `from pylab import *` (fixed with https://github.com/matplotlib/matplotlib/pull/6730/commits/30caf00b60d8fe94c151d3d87670d355275d0568)
   - [x] Solve strange failures on several tests
     - [x] `test_subplots.test_subplots_offsettext` (PR #6741)
     - [x] `test_axes.test_eventplot_problem_kwargs` (PR #6761)
     - [x] `test_pickle.test_complete` (PR #6840)
   - [x] Ensure that pytest collects all the tests (6150/6150) (actually nose shows 6151 because it counts  `lib/matplotlib/tests/test_delaunay.py::make_all_2d_testfuncs` as a test)
2. [x] Migration to pytest
   - [x] Add new build under `allow_failures` with pytest 
     - [x] Appveyor
     - [x] Travis
     - [x] Use `pytest-cov` for coverage reports
   - [x] Replace nose in all builds with pytest
3. [x] Post-migration
   - [x] Rename `setUp` -> `setup_method` and other methods to `pytest` analogs
     - [x] Do not inherit tests from `unitest.UnitTest` class
     - [x] Remove `setUp`/`tearDown`  workaround
   - [x] Rewrite `image_comparison` decorator (currently it slowdowns the collection phase due to baseline images copying) or use `pytest-mpl` plugin (needs some improvements, see paragraph below)
   - [x] Rewrite all assertations to pure `assert`
   - [x] Get away from `cleanup` decorator
   - [x] Replace `knownfailif` with `mark.xfail`
   - [x] Replace `raise nose.SkipTest(...)` with `xfail(...)` call or `mark.skipif` decorator
4. [ ] Enhancements
   - [ ] Replace `setup_method` and etc methods with fixtures
   - [ ] ~~Rewrite `test_delaunay.make_all_2d_testfuncs`~~
   - [x] Use `pytest-pep8` plugin instead of `test_coding_standards`
   - [ ] ~~Use `pytest-mock` plugin instead of `mock` and `unittest.mock`~~
### Tests entry point (raised in https://github.com/matplotlib/matplotlib/pull/5405#issuecomment-154600278)

I think that running tests with simple `py.test` command is better than `python tests.py`, but there are unused tests which will run that way. Solutions:
- A. Get them away from pytest's sight with:
  1. [ ] ~~Remove unused tests (`test_sankey`, `test_skew`, `test_ttconv`, and `test_usetex` from `lib/matplotlib/tests`)~~
  2. [x] Rename `test_only.py` (to `setup_test_only.py` probably)
- B. Make filter for collection phase.
  1. [x] Implement whitelist
  2. [x] Implement blacklist

I have tried both ways and they work, so what to choose is up to you.
- `py.test --collect-filter=none`
- `py.test --collect-filter=blacklist`
- `py.test --collect-filter=whitelist`

Currently `--collect-filter=whitelist` is default (to follow same politics as nose does currently).
### Image comparison decorator

Why do we have to rewrite `image_comparison` decorator? Because `pytest-mpl` plugin in the current state ("as is") is not usable for matplotlib:
- \+ supports `savefig_kwargs`
- \+ supports `tolerance`
- ‒ need to supply `baseline_dir` in every decorator
- ‒ does not support image format conversion
- ‒ need something to do with `freetype_version`, `remove_text`, and `style`

**Comment by story645** [comment]
> Do not inherit tests from unittest.UnitTest class

As someone who's a big fan of these, what's the rational? Unlike nose, it's part of the standard library and it doesn't seem like it's likely to be deprecated.

**Comment by QuLogic** [comment]
There are converters for [nose](https://pypi.python.org/pypi/nose2pytest) and [unittest](https://pypi.python.org/pypi/unittest2pytest), though they aren't totally perfect.

**Comment by story645** [comment]
Yeah, I guess my question is "will pytest not run unittest" tests? Like I understand dumping nose 'cause it's deprecated, but I don't get the issue with unittest unless it explicitly won't work with pytest

**Comment by Kojoley** [comment]
They will work and the are working (pytest handles them with some internal loader hacking in `_pytest.unitest`). But it is useless import of a module that actuality does not used, and you can do [same and even more more with pytest](http://pytest.org/latest/xunit_setup.html)

**Comment by tacaswell** [comment]
We would work with @astrofrog to get the features we need in `pytest-mpl`.

**Comment by jenshnielsen** [comment]
@tacaswell are you sure we want to do that. It's the opposite of what @mdboom suggested in #5405

**Comment by astrofrog** [comment]
@tacaswell - I'd be happy to chat about this at SciPy (over lunch or dinner)

**Comment by astrofrog** [comment]
Regarding the negatives for pytest-mpl:

> ‒ need to supply baseline_dir in every decorator

Actually this is not quite correct - there is a default value which is a folder called ``baseline`` relative to the test. I can also easily add a global setting.

> ‒ does not support image format conversion
> ‒ need something to do with freetype_version, remove_text, and style

I don't think there's any reason we can't add all this, and I don't think it should be that difficult. I'd love to work with you all to make pytest-mpl suitable for matplotlib!

**Comment by QuLogic** [comment]
Another point: we need to get rid of the `yield`-based tests; they are causing tons of warning in the pytest built.

**Comment by QuLogic** [comment]
The `yield`-based tests are fixed, but do we still have a problem of not being able to use `xdist`?

**Comment by Kojoley** [comment]
> The `yield`-based tests are fixed, but do we still have a problem of not being able to use `xdist`?

It looks like we can. At least I have tried and it is good. PR #7468 is opened.

**Comment by jnothman** [comment]
In my own project using pytest, attempting to use `@image_comparison` seems to make the test undetected by pytest. This seems to contradict https://github.com/matplotlib/matplotlib/blob/0d5a02a4e118eb098b78ea00039acd06310e54be/doc/devel/testing.rst. Is it known behaviour?

**Comment by dopplershift** [comment]
Are you aware of https://github.com/matplotlib/pytest-mpl ?

**Comment by tacaswell** [comment]
@jnothman This will be in the 2.1 release so unless you have installed from source you will not have it.

pytest-mpl is probably a better option.

**Comment by jnothman** [comment]
Yes, I'm using pytest-mpl, but having trouble where fonts get in the way,
and for the same reasons would rather compare something other than PNG. But
I may have merely failed to get the freetype font defaulting working and
life may be better when I do.

**Comment by dopplershift** [comment]
@jnothman Have you seen the `remove_text` option for `image_comparison`?

**Comment by phobson** [comment]
I think we can close this now. Is that the case?

**Comment by QuLogic** [comment]
There are still items unchecked that need to be implemented or decided to ignore.

**Comment by phobson** [comment]
Items I think we should ignore:

  * rewrite `image_comparison` decorator. (this is an enhancement and clearly not a prerequisite)
  * rewrite all assertions to pure `assert`. (i think numpy.testing.assert_* should stay as-is)
 
I'm -0 on using `pytest-mock` (like all testing libraries, its docks assume I already know way more than I do)

**Comment by timhoffm** [comment]
I've marked

> Rewrite all assertations to pure assert

as done. I agree with @phobson that `numpy.testing.*` functions should be kept. All other asserts are already written.

**Comment by anntzer** [comment]
I decided to strikeout the "use pytest-mock" line (agreeing with @phobson above); unittest.mock works just fine in the rare cases where we use it and bringing in a new dependency seems overkill (unless someone has a good use case for it in the test suite, in which case please speak up :)).

**Comment by anntzer** [comment]
The "rewrite image_comparison (currently it slows down collection due to baseline image copying)" item seems not true anymore:
1) image copying only occurs in compare() now, not when collecting.
2) #10222 replaces copies by symlinks; at some point it gave a decent speedup but I can't repro it anymore at least locally.

**Comment by anntzer** [comment]
Technically there is one setup_method left in test_transforms.py, but in that specific case it doesn't seem worthwhile to remove it.
I'm thus declaring this issue closed :) Thanks to all for worked on it!
