### ISSUE TITLE
Suggested improvements to the gallery

### ISSUE THREAD

**Issue by anntzer** [matplotlib/matplotlib#7956]
These are all incremental improvements that should be relatively noncontroversial -- assuming we don't go the route of just rewriting the entire thing from scratch.  If you are a committer, feel free to edit the list below to either add items or mark them as done.

- [ ] http://matplotlib.org/devdocs/examples/api/histogram_path_demo.html: Came in in https://github.com/matplotlib/matplotlib/commit/cd88e290401a0c568b0c13ea56692c03fb09e29d, technique seems quite low-level, corresponding animation example was removed three years ago in https://github.com/matplotlib/matplotlib/pull/2779.
- [ ] http://matplotlib.org/examples/images_contours_and_fields/streamplot_demo_features.html http://matplotlib.org/examples/images_contours_and_fields/streamplot_demo_masking.html http://matplotlib.org/examples/images_contours_and_fields/streamplot_demo_start_points.html: should be merged in a single example.
- [ ] http://matplotlib.org/examples/lines_bars_and_markers/fill_demo.html
http://matplotlib.org/examples/lines_bars_and_markers/fill_demo_features.html slightly misleading, xref #5827.
- [ ] http://matplotlib.org/examples/lines_bars_and_markers/fill_demo_features.html http://matplotlib.org/examples/lines_bars_and_markers/fill_demo.html: merge
- [ ] http://matplotlib.org/examples/pylab_examples/equal_aspect_ratio.html: relies on `plt.axes()` to return the already existing implicit axes, which is not really documented directly; should use `plt.gca()` instead (given that it's a pylab example).
- [ ] http://matplotlib.org/examples/pylab_examples/tex_demo.html http://matplotlib.org/examples/pylab_examples/tex_unicode_demo.html: merge.
- [ ] #7878 modified examples/pylab_examples/vline_hline_demo.py to use `blended_transform_factory`, but that's really overkill: see https://github.com/matplotlib/matplotlib/pull/7878#issuecomment-273948869.

----

- [x] http://matplotlib.org/examples/api/sankey_demo_old.html: remove (we have builtin support for such diagrams now).  Done in #7972.
- [x] http://matplotlib.org/examples/pylab_examples/newscalarformatter_demo.html: drop OldScalarFormatter (which should probably be deprecated anyways...) and use one formatter per subplot.
- [x] http://matplotlib.org/examples/misc/sample_data_demo.html: remove, users should probably not rely on sample data.  Done in #7972.
- [x] http://matplotlib.org/examples/pylab_examples/spectrum_demo.html: add tight_layout() call. Done in #8158.
- [x] http://matplotlib.org/examples/pylab_examples/accented_text.html http://matplotlib.org/examples/text_labels_and_annotations/unicode_demo.html: remove #8065 
- [x] http://matplotlib.org/examples/pylab_examples/matshow.html: only keep middle plot Done in #8094
- [x] http://matplotlib.org/examples/pylab_examples/manual_axis.html: remove (deprecated)  Done in #7972.
- [x] http://matplotlib.org/examples/pylab_examples/text_handles.html: remove; it refers to an apparently non-existing `text_themes` examples which may be worth restoring (perhaps)  Done in #7972.
- [x] http://matplotlib.org/examples/pylab_examples/toggle_images.html: remove or move to event handling section.  Done in #7972.

attn @NelleV

**Comment by story645** [comment]
On the pylab example, I support your decision and propose a drastic reduction in pylab examples. Like a 5-10 line example of each of the main plot types: bar, line, scatter, heat, and maybe one or two scientific plots (like tricolor or whatever) and hist. Anything more than that, I think their should just be some large text at the top of the pylab examples page that says "besides these, the following plot types are also available in pylab: list" and possibly one example with the OO side by side with the pylab to show readers how to translate OO examples to pylab notation.

**Comment by NelleV** [comment]
By experience, any and all documentation changes is controversial :)

**Comment by Morillo9** [comment]
Hi, I am a new and I would like to contribute. Is one of the issues especially well suited for a new contributor?

**Comment by anntzer** [comment]
- http://matplotlib.org/examples/pylab_examples/accented_text.html http://matplotlib.org/examples/text_labels_and_annotations/unicode_demo.html: remove

looks like an easy place to get started.

**Comment by helmiriawan** [comment]
Hi, I am a new and I would like to contribute. Is there anyone who work on tex_demo examples?

**Comment by anntzer** [comment]
Not as far as I can see.

**Comment by NinadBhat** [comment]
Is some working on 
 http://matplotlib.org/examples/pylab_examples/equal_aspect_ratio.html: relies on plt.axes() to return the already existing implicit axes, which is not really documented directly; should use plt.gca() instead (given that it's a pylab example)?
I will like to take it.
Thanks

**Comment by pssk1988** [comment]
Beginner here:  Let's say I would like to solve this issue.  http://matplotlib.org/examples/pylab_examples/tex_demo.html http://matplotlib.org/examples/pylab_examples/tex_unicode_demo.html: merge.

How to perform the modifications? I do not see any page to log in and make changes.

**Comment by story645** [comment]
You make the changes in the source python file that the html is generated from.. For example, tex_demo.html is generated from https://github.com/matplotlib/matplotlib/blob/master/examples/pylab_examples/tex_demo.py

**Comment by pssk1988** [comment]
Oh yeah. Just forked the code from github. Thanks!

**Comment by darrenzhang2000** [comment]
Hi, I am a beginner here. May I solve the following issue?
http://matplotlib.org/examples/lines_bars_and_markers/fill_demo.html

**Comment by story645** [comment]
@darrenzhang2000 go for it!

**Comment by ImportanceOfBeingErnest** [comment]
The `fill_demo` was removed between version 2.0 and 2.1. So I fear there is nothing to be done anymore. I marked this point as solved by #11009, which changed `fill.py` accordingly.

**Comment by devarshigoswami** [comment]
If this issue still persists, can I be assigned to it??

**Comment by story645** [comment]
Closing since all the tasks appear to be completed.
